#!/usr/bin/env python3

import argparse
from collections import defaultdict
import csv
from datetime import datetime
from distutils.spawn import find_executable
import gzip
import os
import pathlib
import pyfastx
import shutil
import subprocess
import sys

AUTHOR = "Anicet Ebou <anicet.ebou@gmail.com>"
URL = "https://github.com/Ebedthan/mashphage.git"
VERSION = "0.1.0"

# Define start time----------------------------------------------------------
startime = datetime.now()
helptime = datetime.now().strftime("%a, %d %b %Y %H:%M:%S")

# Define command-line arguments----------------------------------------------
parser = argparse.ArgumentParser(
    prog="mashphage",
    formatter_class=argparse.RawDescriptionHelpFormatter,
    usage="mashphage [options] seqs.fa.gz",
    epilog=f"Version:   {VERSION}\nLicence:   GPL-3\n"
    + f"Homepage:  {URL}\nAuthor:    {AUTHOR}\nLast Run:  {helptime}.",
)

parser.add_argument("seqs", help="Specify input sequences fasta file")
parser.add_argument(
    "--out",
    help="Specify output file",
    nargs="?",
    type=argparse.FileType("a"),
    default=sys.stdout,
)
parser.add_argument(
    "--cpus", type=int, default=1, help="Specify the number of threads"
)
parser.add_argument(
    "--debug", action="store_true", help="Activate debug mode"
)
args = parser.parse_args()


def main():
    # Handling db directory path specification-------------------------------
    try:
        dbdir = os.environ["MASHPHDB"]
    except KeyError:
        print(
            "mashphage: error: Mash sketch reference file not "
            + "found in $PATH.",
            file=sys.stderr,
        )
        print(
            "Please set MASHPHDB environment variable to the path "
            + "where the file is stored.",
            file=sys.stderr,
        )
        print(
            "Visit https://github.com/Ebedthan/mashphage for more",
            file=sys.stderr,
        )
        sys.exit(1)

    # Start program ---------------------------------------------------------
    print("-----------------------------------------------")
    print("mashphage Copyright (C) 2021 Anicet Ebou")
    print("This program comes with ABSOLUTELY NO WARRANTY;")
    print("This is free software, and you are welcome to ")
    print("redistribute it under certain conditions.")
    print("-----------------------------------------------")
    print(f"mashphage version {VERSION}")

    # Handling number of cpus -----------------------------------------------
    cpus = args.cpus

    if args.cpus == 0:
        cpus = os.cpu_count()
    elif args.cpus > os.cpu_count():
        cpus = os.cpu_count()

    # Verify presence of mash -----------------------------------------------
    if find_executable("mash") is None:
        print(
            "Mash was not found on your system."
            + " Please install it at https://github.com/Marbl/mash.git"
        )
        sys.exit(1)

    # Test if file is gzipped -----------------------------------------------
    if is_gz_file(args.seqs):
        with gzip.open(args.seqs, "r") as seqh:
            with open(pathlib.Path(args.seqs).stem, "wb") as seqo:
                shutil.copyfileobj(seqh, seqo)
            seqo.close()
        inpath = pathlib.Path(args.seqs).stem
    else:
        inpath = args.seqs

    # Build input sequence index for query ----------------------------------
    infax = pyfastx.Fasta(inpath)
    seqids = infax.keys()
    try:
        os.removedirs("tmpfa")
    except OSError:
        pass

    # Create tmp folder
    os.mkdir(pathlib.Path("tmpfa"))

    for seqid in seqids:
        with open(f"tmpfa/{seqid}", "w") as tfa:
            with open("falist.txt", "a") as lf:
                tfa.write(f">{seqid}\n{infax[seqid]}\n")
                lf.write(f"tmpfa/{seqid}\n")
            lf.close()
        tfa.close()

    # Run mash -----------------------------------------------------
    with open("mashdist.out", "w") as outfile:
        subprocess.run(
            [
                "mash",
                "dist",
                "-l",
                "-p",
                str(cpus),
                pathlib.Path(dbdir, "reference.msh"),
                "falist.txt",
            ],
            stdout=outfile,
        )

    # Parsing result --------------------------------------------------------
    resdict = defaultdict(dict)
    sortres = {}
    with open("mashdist.out") as mof:
        rd = csv.reader(mof, delimiter="\t")
        for row in rd:
            resdict[row[1]][row[0]] = [row[2], row[3]]
    mof.close()

    for k, d in resdict.items():
        minv = min((i for i in d.values()), key=lambda x: x[0])
        sortres[k] = {list(d.keys())[list(d.values()).index(minv)]: minv}

    # Writing output --------------------------------------------------------
    outfile = args.out
    outfile.write("sequence_id\tpredicted_cluster\tmash_distance\tP-value\n")
    for key, value in sortres.items():
        for x, j in value.items():
            outfile.write(
                f"{pathlib.Path(key).stem}\t"  # sequence id
                + f"{x}\t"  # cluster
                + f"{j[0]}\t"  # mash distance
                + f"{j[1]}\n"  # p-value
            )
    try:
        outfile.close()
    except ValueError:
        pass

    # Cleaning around -------------------------------------------------------
    shutil.rmtree("tmpfa")
    os.remove("falist.txt")
    os.remove("mashdist.out")
    os.remove(pathlib.Path(f"{inpath}.fxi"))

    endtime = datetime.now()
    walltime = endtime - startime
    print(f"Walltime used (hh:mm:ss.ms): {walltime}")
    if len(seqids) % 2:
        print("Nice to have you. Share, enjoy and come back!")
    else:
        print("Thanks you, come again.")


def is_gz_file(fp):
    """
    is_gz_file test if input filepath is gzipped or not.

    :fp: Path to input file
    """

    with open(fp, "rb") as test:
        return test.read(2) == b"\x1f\x8b"


def exception_handler(
    exception_type, exception, traceback, debug_hook=sys.excepthook
):
    """
    exception_handler remove default debug info and traceback
    from python output on command line. Use program --debug
    option to re-enable default behaviour.
    """

    if args.debug:
        debug_hook(exception_type, exception, traceback)
    else:
        print(f"{exception_type.__name__}, {exception}")


sys.excepthook = exception_handler

if __name__ == "__main__":
    main()
